#!/bin/bash

# List of all staged go.mod files
MOD_FILES=$(git diff --cached --name-only | grep "go.mod")

# Loop over all go.mod files and check if they contain the replace directive
for MOD_FILE in $MOD_FILES
do
  if grep -q 'replace' $MOD_FILE; then
    echo "ERROR: $MOD_FILE contains a replace directive"
    exit 1
  fi
done

# List all staged go files
STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  printf "No Go files staged. Skipping pre-commit hook."
  exit 0
fi

for FILE in $STAGED_GO_FILES
do
  # Format & stage any staged file that succeeds vet
  gofmt -e -s -w $FILE
  git add $FILE
done

# Format the entire directory but dont stage it.
gofmt -e -l -s -w .

exit 0
